language: python
dist: xenial
      
matrix:
  include:
  - stage: tox
  - python: '3.6'
    env: TOXENV=py36
  - python: '3.7'
    env: TOXENV=py37
    install:
      - python -mpip install --progress-bar=off tox-travis
    script:
      - tox -v
  - stage: test
    python: '3.7'
    install:
      - pipenv install --dev --ignore-pipfile --deploy
    before_script: # code coverage tool
      - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - chmod +x ./cc-test-reporter
      - ./cc-test-reporter before-build
    script: pytest --cov-report xml --cov-report term
    after_script:
      - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

stages:
  - test
  - tox