language: python
python: 3.7
dist: xenial
cache: false
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
matrix:
  include:
    - env:
        - TOXENV=py36
      python: '3.6'
      stage: tox
      ...
    - stage: test
      python: '3.7'
    install:
      - pipenv install --dev --ignore-pipfile --deploy

    before_script: # code coverage tool
              - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
              - chmod +x ./cc-test-reporter
              - ./cc-test-reporter before-build
    script: pytest --cov-report xml --cov-report term
    after_script:
      - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
stages:
  - test
  - tox
notifications:
  email:
    on_success: never
    on_failure: always
